### ISSUE TITLE
Mirror tags for new patch releases of older major/minor release series

### ISSUE THREAD

**Issue by dokempf** [pre-commit/pre-commit-mirror-maker#123]
The current mirror implementation restricts only adds new versions if their version is higher than the newest version already present on the mirror (code here: https://github.com/pre-commit/pre-commit-mirror-maker/blob/master/pre_commit_mirror_maker/make_repo.py#L80). This is a good solution if assuming that people will always want to update to the latest version.

In https://github.com/ssciwr/clang-format-wheel and its mirror in https://github.com/pre-commit/mirrors-clang-format we are supporting multiple major/minor versions (after all upgrading to a newer version of clang-format might rewrite your code base). I have released versions `10.0.1.1`, `11.0.1.1`, 11.1.0.1` and `12.0.1.1` last week that fix two packaging issues on Windows, but these releases are not picked up by the mirror.

I propose to either unconditionally or via an additional flag have `pre-commit-mirror` take into account the entire list of releases. What do you think?

**Comment by asottile** [comment]
the history only moves forward, backporting is intentionally not supported

**Comment by dokempf** [comment]
That sounds like a reasonable approach for most hooks, but is quite unfortunate for the specific case of `clang-format`. Unfortunately for me, it also invalidates a good deal of my efforts in packaging clang-format. The only way forward I can currently see is to reenable the old hook repository at https://github.com/ssciwr/clang-format-hook and provide backports on that one. If you see another solution, I would love to hear it.

**Comment by aentwist** [comment]
It is worse than that: it doesn't distinguish between whether the version is stable or not. Now https://github.com/pre-commit/mirrors-prettier has v4.0.0-alpha.8, which released after 3.1, but has not published 3.2.

**Comment by asottile** [comment]
that's a different issue
