### ISSUE TITLE
Add support for Golang

### ISSUE THREAD

**Issue by yehoshuadimarsky** [pre-commit/pre-commit-mirror-maker#124]
Hi, thanks for this tool, I see there is no support for Golang. Is that intentional or just not enough users that want it?

**Comment by asottile** [comment]
it just hasn't been implemented 🤷 

when this tool was written (2014) there was no good way to "version" golang (go mod didn't exist) so it was not attempted -- plus `pre-commit` didn't support golang until 2017

if you're interested in supporting this, send a PR!

**Comment by yehoshuadimarsky** [comment]
Yes I'll make a PR, just not super clear on the requirements - Golang doesn't have a central artifact site like PyPI or NPM, so how do I make a repo mirror - where do I specify what it should point at?

**Comment by asottile** [comment]
I'm not really sure!  probably you'd write out a `go.mod` file ? or leverage `additional_dependencies` if `go.mod` doesn't work?
