### ISSUE TITLE
Support for creating mirrors of Golang-based tools

### ISSUE THREAD

**Issue by Jarmos-san** [pre-commit/pre-commit-mirror-maker#164]
Is there any way for `pre-commit-mirror` to create mirrors of tools developed using Go? So far I can only see support for Python, Node, Rust & Ruby tools.

**Comment by asottile** [comment]
it's certainly possible, but would need someone to implement go support

a reminder that the mirror maker is a stopgap and it is preferred for the actual repo to have the pre-commit metadata

**Comment by Jarmos-san** [comment]
Closing it since its now officially supported (see this PR https://github.com/errata-ai/vale/pull/558)

**Comment by trallnag** [comment]
FYI: Opened a another issue for this as it still would be helpful
