### ISSUE TITLE
Github actions are outdated in the mirror repos 

### ISSUE THREAD

**Issue by jooola** [pre-commit/pre-commit-mirror-maker#167]
I see that some mirror repositories have outdated actions, for example:

https://github.com/pre-commit/mirrors-eslint/blob/b9e2cdf31698b333834bc6d6641a18579b71cdbf/.github/workflows/main.yml#L13-L14

I am unsure how this should be fixed, if you @asottile prefer to update this manually with your own tools, or if  a dependency bot setup would be welcome for the mirror repositories. I am unsure if such config can be pushed using the pre-commit mirror maker tool.

Maybe a flag can be added to automatically add a workflow definition depending on the requirements of the mirror.

Bumping the version manually is probably less verbose, but it will not be automatic for future version updates.

**Comment by asottile** [comment]
and why does this matter? who cares?

**Comment by jooola** [comment]
Because the workflows are using unmaintained actions. For example the checkout action v1 is unmaintained.

What it could improve is performance, security, and what it could prevent is breaking unexpectedly. In general I think it is a good practice.

**Comment by asottile** [comment]
please don't waste my time unless there's actually a good reason -- hypotheticals are not helpful
