### ISSUE TITLE
[question] is it support `always_run`, ...?

### ISSUE THREAD

**Issue by Freed-Wu** [pre-commit/pre-commit-mirror-maker#170]
> always_run
> (optional) if true, this hook will run even if there are no matching files.
> verbose
> (optional) if true, forces the output of the hook to be printed even when the hook passes.
> log_file
> (optional) if present, the hook output will additionally be written to a file when the hook fails or verbose is true.

**Comment by asottile** [comment]
do you see it in the options?

`always_run` is usually a mistake
