### ISSUE TITLE
Allow arbitrary hook config entries by generically converting CLI args

### ISSUE THREAD

**Issue by aentwist** [pre-commit/pre-commit-mirror-maker#199]
## User Story

I have a hook that takes no files, yet

```
error: one of the arguments --files-regex --types --types-or is required
```

Also, I have no way to specify any of

```yaml
stages: [commit-msg, manual]
pass_filenames: false
always_run: true
```

## Proposed Solution

I propose the CLI args be generically converted to hook config entries. I believe this will solve all of the above and provide more flexibility with less coupling overall.

That is,

```shell
pre-commit-mirror [...] --stages=commit-msg,manual --pass-filenames=false --always-run=true  # no files or types specified
```

gets config similar to the above.

**Comment by asottile** [comment]
a hook which does not take files does not adhere to the interface required by pre-commit.  it's unsupported and so special support here for such a hook does not make sense (it would encourage a sub-par experience for the user)

**Comment by aentwist** [comment]
I'm confused - that seems to directly contradict the mission statement, and pre-commit still provides options to interact with such hooks? Does that mean the official stance is 'possible, but not supported' (out of scope)? And as for how I should proceed - the suggestion then might be to have users set up a node environment manually in their CI to run this type of hook in CI? Thanks for the direction, I appreciate your time.

**Comment by asottile** [comment]
pre-commit operates best when it manages the tools and operates on files via established repositories.

there are escape hatches to enable people to continue in unsupported territory but they are generally a worse experience (`language: script`, `language: system`, `additional_dependencies`, `always_run`, `pass_filenames`, `repo: local`, `require_serial`, etc.)

> for how I should proceed

impossible to tell -- you haven't told me what you're _trying_ to do -- I suspect you have an XY problem but I can't tell when you have instead showed me the Y and not the X you're trying to do
