### ISSUE TITLE
Skip alpha/beta versions

### ISSUE THREAD

**Issue by jirikuncar** [pre-commit/pre-commit-mirror-maker#202]
`mirrors-prettier` contains `alpha` tags that cause issues when running `pre-commit autoupdate`.

Is it possible/desirable to skip synchronization of `alpha/beta/pre` releases?

## Alternatives

- Add a flag to `pre-commit autoupdate` that prevents updating to non-stable versions.

**Comment by asottile** [comment]
please search for duplicates next time
