### ISSUE TITLE
mirrors-prettier missing tags >3.1.0,<4.0.0

### ISSUE THREAD

**Issue by dbowring** [pre-commit/pre-commit-mirror-maker#207]
`mirrors-prettier` appears to be ignoring 3.x releases made after the first [v4-alpha](https://github.com/prettier/prettier/releases/tag/4.0.0-alpha.4) release. Currently, this means `3.1.1` through `3.2.5` are not available from the mirror.

**Comment by asottile** [comment]
there are many duplicates, please search next time
