### ISSUE TITLE
"make venv" doesn't work

### ISSUE THREAD

**Issue by chriskuehl** [pre-commit/pre-commit-mirror-maker#32]
There's a makefile target but no corresponding tox environment:

```
$ make venv 
touch .venv.touch
tox -e venv --recreate
ERROR: unknown environment 'venv'
Makefile:9: recipe for target 'venv' failed
make: *** [venv] Error 1
```

**Comment by asottile** [comment]
Looks like I (inadvertently?) removed it while dropping python2 support: https://github.com/pre-commit/pre-commit-mirror-maker/commit/d4c5708418272e0de95da2695bf9ed63b67950f1#diff-b91f3d5bd63fcd17221b267e851608e8

Leaning towards just `git rm Makefile` -- unless there's a usecase for it (I've mostly been using `tox -e py36` myself)

**Comment by chriskuehl** [comment]
:shipit:

**Comment by asottile** [comment]
via 51510d10f999048f963b6da3a7e33c087166eecc
