### ISSUE TITLE
Help output and usage example in README are outdated

### ISSUE THREAD

**Issue by chriskuehl** [pre-commit/pre-commit-mirror-maker#33]
Some flags are no longer positionals, plus there are some new ones not in the README.

Should we just delete it and tell people to run `--help` themselves? Or update it?

**Comment by asottile** [comment]
ah yeah, I was planning to update this after completing #31 and making a release -- until then it matches the _released_ options (not ideal, but easy to fix).

Probably worth just deleting and suggesting `--help`
