### ISSUE TITLE
How to setup release to include config attributes

### ISSUE THREAD

**Issue by adithyabsk** [pre-commit/pre-commit-mirror-maker#56]
It seems that the script overwrites the yaml confile by default (instead of updating it). If I need to maintain a config param such as `pass_filenames: false`. How would I go about doing that?

The repo in question: https://github.com/adithyabsk/mirrors-brakeman

**Comment by asottile** [comment]
you would add a feature to pre-commit-mirror-maker to populate that option, the intention is that it manages the necessary pre-commit configuration and components completely

**Comment by adithyabsk** [comment]
@asottile Okay, quick question, trying to dig into this and run tests locally. What is the `pre-commit` env in the tox envlist, is that a local virtualenv?

**Comment by asottile** [comment]
it's just to run this command: https://github.com/pre-commit/pre-commit-mirror-maker/blob/1c5b45349407f930f1c238b96864d851b0e68d7d/tox.ini#L15

**Comment by adithyabsk** [comment]
@asottile Just added a patch in patch in PR #57
