### ISSUE TITLE
Allow `id:` to be configured as part of pre-commit-mirror-maker

### ISSUE THREAD

**Issue by lcnittl** [pre-commit/pre-commit-mirror-maker#62]
Currently, `id` seems to be always equaling `entry`:

https://github.com/pre-commit/pre-commit-mirror-maker/blob/aea1d0ff0765295f779cc2e8dc5a43d05bcb3887/pre_commit_mirror_maker/all/.pre-commit-hooks.yaml#L1-L3

There are, however, cases where `entry` needs to contain some default, non-overridable arguments which would then make `id` unnecessarily long and ugly (especially if the repo has only one hook):

```
$ git init mirrors-CleverCSV
$ pre-commit-mirror mirrors-CleverCSV --language python --package-name clevercsv --entry "clevercsv standardize --in-place" --types csv
```

Or is this not worth the work, as usually the repo configs are anyways just copy pasted?

**Comment by asottile** [comment]
seems fine to add an option to override one or the other, none of the existing things needed it

for your particular example I'd recommend putting `--in-place` into `args: [...]` but yeah it makes sense that the entry is `clevercsv standardize`

**Comment by lcnittl** [comment]
Is it ok that I create a PR for this?

**Comment by asottile** [comment]
yes, that was what I was suggesting by the [help wanted] tag

**Comment by lcnittl** [comment]
> yes, that was what I was suggesting by the [help wanted] tag

Oh, sh*t. Looks like I never really understood what that tag means 🙈 Anyways, PR is out.
