### ISSUE TITLE
Support for packages with "extras"

### ISSUE THREAD

**Issue by lcnittl** [pre-commit/pre-commit-mirror-maker#63]
I ran across the issue to (have to) mirror a package which needs "extras" to function:

```
pre-commit-mirror mirrors-CleverCSV --language python --package-name "clevercsv[full]" --entry "clevercsv standardize" --args="--in-place" --types csv
```

The extras are of course not part the PyPI URL, where `package-name` gets inserted to:

https://github.com/pre-commit/pre-commit-mirror-maker/blob/aea1d0ff0765295f779cc2e8dc5a43d05bcb3887/pre_commit_mirror_maker/languages.py#L21-L24

Yet, the resulting `setup.py` needs to have `clevercsv[full]` in its `install_requires` that the installed package can function properly → Thus, one would need to strip off any `[..]` from the `package_name` for URL creation.

Is it too ugly to just do a `package_name.split("[")[0]`? Should be save though, as a bracket should not be an allow character in package names.

PS: Sorry for all the spam, this is the last one, i promise 😉

**Comment by asottile** [comment]
probably two ways to approach this:

(1) add an `--extras` (though this is probably too specific to python to be useful for others)
(2) parse *just* the package name out of the `package_name` -- [.partition(...)](https://youtu.be/kx6G3nkZTjM) is probably a slightly better `.split(...)` there.  or it could parse the actual requirement using `packaging` (already a dependency)

```pycon
>>> packaging.requirements.Requirement('foo[bar]').name
'foo'
```

**Comment by lcnittl** [comment]
Nice video! I didn't know about `partition`.

I agree that (1) might be too specific, but also have to admit that I know hardly anything about the other packaging indexes and their "syntax" of package names/add-ons/extras or whatsoever.

Thanks anyways for looking into it!

**Comment by asottile** [comment]
yeah I'd suggest going with (2) via `packaging`
